== Finding components
:imagesdir: images
:sourcedir: ../../test

'''

One of the most important Tyro's features is its flexibility and power to find UI components.
As we discussed earlier, Tyro is based on an abstraction of the UI. So to give you the best experience Tyro has many ways
to find components. It's yours to use what suits your case.

=== The $ function

The $ function is the access point for fetching components on the page. The $ function accepts a selector to target your component.

The expression is pretty simple and always follows the same pattern:
[source, groovy]
----
    Abstraction component = $('*the selector*') as Implementation
----

[IMPORTANT]
====
*Tyro* is typed.

The *$* selector is to find/locate the component, the *as* is to verify that the component is the expected type.
====

Tyro is based on an abstraction but comes with a default implementation: the Web implementation based on Selenium.

This base implementation accepts the powerful https://api.jquery.com/category/selectors/[JQuery selectors] to find components in your page.



Our experience demonstrated that *we never need complex selector.* Especially if you write tests first, a simple finding expression will push you to write clean html components (example : only one button with a given label in the same page). 

In the code, this is reflected by a custom tag, the sequence in the page, a role attribute, or an id. In all these cases, a css3 selector is more than enough.

[NOTE]
====
The $ function *NEEDS* to target a *UNIQUE* component. If Tyro finds several components for the selector, it simply fails!
For multiple selection use $$ function.
====

==== Examples

*A TextField by id.*
[source, groovy]
----
    TextField textfield = $('[id="myId"]') as InputTypeText
    TextField textfield = $('#myId') as InputTypeText // Shortcut
----

*[green]#TextField#* is the abstraction and *[blue]#InputTypeText#* is the implementation for the targeted technology (in this case Html5)

[IMPORTANT]
====
the shortcut *# cannot be used for ids with '.' inside* (_not supported by JQuery_)
====

*A TextField by class.*
[source, groovy]
----
    TextField textfield = $('[class="myClass"]') as InputTypeText
    TextField textfield = $('.myClass') as InputTypeText // Shortcut
----

*A TextField by name.*
[source, groovy]
----
    TextField textfield = $('[name="myName"]') as InputTypeText
----

*A TextField by data-role.*
[source, groovy]
----
    TextField textfield = $('[data-role="myRole"]') as InputTypeText
----

*The second TextField in the page corresponding to an input html tag with type = 'text'.*
[source, groovy]
----
    TextField last_name = $('input:eq(1)') as InputTypeText
----

*The first Heading element in the page corresponding to an h3 html tag.*
[source, groovy]
----
    Heading sectionSubTitle = $('h3:eq(0)') as H3
----

*The third Button in the page with 'myName' name.*
[source, groovy]
----
     Button go_button =  $('[name="myName"]:eq(2)') as sc.tyro.bundle.html5.Button
----
*The first DataGrid in the form with 'myName' name.*
[source, groovy]
----
      DataGrid getOperationTable = $('form[name="myName"] > table:eq(0)') as Table
----

[IMPORTANT]
====
The selected component *MUST BE TYPED* through the *"as"* keyword.
====


=== The $$ function

The $$ function follows the sames rules of $ function except it returns a list of components.

[IMPORTANT]
====
These components need to be of the same type.
====

==== Examples

*A List of Items.*

[source, html]
----
  <html>
    <select>
      <option>New-York</option>
      <option>Montpellier</option>
      <option>Chicago</option>
    </select>
  </html>
----


[source, groovy]
----
    List<Item> items = $$('select option', Option)
----

In this example we take the list of Html5 Option components under the Html5 Select component (the 3 towns) and we return them as a list of Items.

=== Using factories

Tyro comes with a bunch of components factories.
Factories should be used as the first way to find components.
In TDD approach this will drive your page design with the best semantic and structure.

*Find Button using its text.*
[source, groovy]
----
    Button button = button('Submit')
----

*Find Radio using its label or placeholder.*
[source, groovy]
----
    Radio radio = radio('label')
----

*Find CheckBox using its label or placeholder.*
[source, groovy]
----
    CheckBox checkbox = checkbox('label')
----

*Find Dropdown using its label or placeholder.*
[source, groovy]
----
    Dropdown dropdown = dropdown('label')
----

*Find Field using its label or placeholder.*
[source, groovy]
----
    Field field = field('label')
    TextField field = field('label', TextField)
----

*Find ListBox using its label or placeholder.*
[source, groovy]
----
    ListBox listBox = listBox('label')
----

*Find Group using its value.*
[source, groovy]
----
    Group group = group('value')
----

*Find Item using its value.*
[source, groovy]
----
    Item item = item('value')
----

*Find Heading using its text.*
[source, groovy]
----
    Heading heading = heading('text')
----

*Find Panel using its title.*
[source, groovy]
----
    Panel panel = panel('title')
----

*Find Link using its text.*
[source, groovy]
----
    Link link = link('text')
----

*Find Component using its text.*
[source, groovy]
----
    Component myComponent = findByText('text', Component)
----

*Find Component using its label.*
[source, groovy]
----
    Component myComponent = findByLabel('label', Component)
----

*Find Component using its value.*
[source, groovy]
----
    Component myComponent = findByValue('value', Component)
----

*Find Component using its title.*
[source, groovy]
----
    Component myComponent = findByTitle('value', Component)
----


[IMPORTANT]
====
Sometimes the UI can contain more than one item with the same test/value/label ...

*Example: Two button with text 'Ok'*

In this case you can scope your search by passing the parent context to the factory method.

*Find Component using its title scoped in parent context*
[source,groovy,linenums]
[subs="verbatim,attributes"]
----
include::{sourcedir}/groovy/sc/tyro/doc/FactoryTest.groovy[tags=factory,indent=0]
----
====