== Interacting with components
:imagesdir: images
:sourcedir: ../../test

'''

In Tyro, interacting with components is very easy and powerful.

=== With Mouse

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
include::{sourcedir}/groovy/sc/tyro/doc/InteractionTest.groovy[tags=mouse,indent=0]
----

[[keyboard]]
=== With Keyboard

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
include::{sourcedir}/groovy/sc/tyro/doc/InteractionTest.groovy[tags=keyboard,indent=0]
----

=== With Actions

Tyro offers an advanced interaction feature. It allows a functional way to interact with components.
It's a good way to minimize common side effects on UI tests.

Through an elegant DSL, you can define an action that will be executed on a component.

// TODO review this sentence
All actions take care of the component, so it can be at least in a minimal expected state before applying action on it:

* [x] available
* [x] enabled
* [x] visible

[[Mouse]]
==== mouse
These actions apply on *all components*.

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
include::{sourcedir}/groovy/sc/tyro/doc/InteractionTest.groovy[tags=mouse-dsl,indent=0]
----

[[check]]
==== check

This action applies on *Checkable* components. If the component is already checked, it will throw an exception.
[NOTE]
====
Syntax is : *check <__component__>*
====

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
include::{sourcedir}/groovy/sc/tyro/doc/InteractionTest.groovy[tags=check,indent=0]
----

[[uncheck]]
==== uncheck

This action applies on *UnCheckable* components. If the component is already unchecked, it will throw an exception.
[NOTE]
====
Syntax is : *uncheck <__component__>*
====

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
include::{sourcedir}/groovy/sc/tyro/doc/InteractionTest.groovy[tags=uncheck,indent=0]
----

[[type]]
==== type
This action is just a shortcut on the <<keyboard>>.

[NOTE]
====
*type 'some text'* (strictly equivalent to *keyboard.type('some text')*)
====

[[fill]]
==== fill

With this action you can fill a field directly without passing by the keyboard.
This must be the preferred way to set value on a field in a form, because most of the time the validation is needed when you leave the field.
In the case you want a validation when entering characters in the field, you must use the keyboard action "type".

This action applies on *Field* Components. 
[NOTE]
====
Syntax is : *fill <__field__> with <__value__>*
====

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
include::{sourcedir}/groovy/sc/tyro/doc/InteractionTest.groovy[tags=fill,indent=0]
----

[[clear]]
==== clear

This action is used to clear a field. Here again it's done directly without passing by the keyboard (just changing the value of the field).

This action applies on *Field* Components. 
[NOTE]
====
Syntax is : *clear <__field__>*
====

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
include::{sourcedir}/groovy/sc/tyro/doc/InteractionTest.groovy[tags=clear,indent=0]
----

[[set]]
==== set

This is the same action as <<fill>>. It's just a better word for suite components like Range, DatePicker, ColorPicker...

This action applies to some *Field* Components.
[NOTE]
====
Syntax is : *set <__field__> to <__value__>*
====

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
include::{sourcedir}/groovy/sc/tyro/doc/InteractionTest.groovy[tags=set,indent=0]
----

[[submit]]
==== submit

This action is used to *submit* a form. It tries to find the expected submit button attached to the form and clicks on it if it's available or fails if it's not.

This action applies on *Submissible* Components. 
[NOTE]
====
Syntax is : *submit <__component__>*
====

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
submit myForm
----

[[reset]]
==== reset

This action is used to *reset* a form. It tries to find the expected reset button attached to the form and clicks on it if it's available or fails if it's not.

This action applies on *Resettable* Components.
[NOTE]
====
Syntax is : *reset <__component__>*
====

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
reset myForm
----

[[switchOn]]
==== switchOn

This is the same action as <<check>>. It's just a better word to suite components like Switch ...

This action applies on *Switchable* components. 
[NOTE]
====
Syntax is : *switchOn <__component__>*
====

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
switchOn darkTheme
----

[[switchOff]]
==== switchOff

This is the same action as <<uncheck>>. It's just a better word to suite components like Switch ...

This action applies on *UnSwitchable* components. 
[NOTE]
====
Syntax is : *switchOff <__component__>*
====

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
switchOff darkTheme
----

[[select]]
==== select

This action applies on *Item* components. If the Item is already selected, it will throw an exception.

This action applies on *Item* components.
[NOTE]
====
Syntax is : *select <__item__>*
====

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
select myItem_1, myItem_2
----

[[unselect]]
==== unselect


This action applies on *Item* components. If the Item is already unselected, it will throw an exception.

This action applies on *Item* components.
[NOTE]
====
Syntax is : *unselect <__item__>*
====

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
unselect myItem_1, myItem_2
----

==== on

This action is just a pass through (a function who returns the passed component).
It's here to improve readability of a test. 
[NOTE]
====
Syntax is : *on <__component__> select <__item__>*   or    *on <__component__> unselect <__item__>*
====

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
include::{sourcedir}/groovy/sc/tyro/doc/InteractionTest.groovy[tags=on,indent=0]
----







