== Interacting with components
'''

In Tyro interacting with component is very easy and powerful.

[NOTE]
====
.The following actions are shared by all Tyro components :
click, rightClick, doubleClick, mouseOver, drag
====

=== With Mouse

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
include::{sourcedir}/test/groovy/sc/tyro/doc/InteractionTest.groovy[tags=mouse,indent=0]
----

=== With Keyboard

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
include::{sourcedir}/test/groovy/sc/tyro/doc/InteractionTest.groovy[tags=keyboard,indent=0]
----

=== With Actions

Tyro offer an advanced interaction feature. It allows a functional way to interact with components.
It's a good way to minimized common side effects on UI tests.

[[check]]
==== check

This action does some assertions and verify that the component is *visible*, *not deactivated* and *not already in the expected state*.
So for example if you try to check a component already checked an exception is thrown.

This action applies on *Checkable* components.

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
include::{sourcedir}/test/groovy/sc/tyro/doc/InteractionTest.groovy[tags=check,indent=0]
----

[[uncheck]]
==== uncheck

This action does some assertions and verify that the component is *visible*, *not deactivated* and *not already in the expected state*.
So for example if you try to unCheck a component already unChecked an exception is thrown.

This action applies on *UnCheckable* components.

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
include::{sourcedir}/test/groovy/sc/tyro/doc/InteractionTest.groovy[tags=uncheck,indent=0]
----

[[fill]]
==== fill

With this action you can fill a field directly without passing by the keyboard.
This is useful in the most case when you set value on a field in a form (Most of the time the validation occur when you leave the field).

This action apply to *Field* Components.

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
include::{sourcedir}/test/groovy/sc/tyro/doc/InteractionTest.groovy[tags=fill,indent=0]
----

[[clear]]
==== clear

This action it's to clear a field. Here again it's done directly without passing by the keyboard (just changing the value of the field).

This action apply to *Clearable* Components.

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
include::{sourcedir}/test/groovy/sc/tyro/doc/InteractionTest.groovy[tags=clear,indent=0]
----

[[set]]
==== set

Set in the same action as <<fill>>. It's just a better word to suite components like Range, DatePicket, ColorPicker...

This action apply to *Field* Components.

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
include::{sourcedir}/test/groovy/sc/tyro/doc/InteractionTest.groovy[tags=set,indent=0]
----

[[submit]]
==== submit

This action is to *submit* a form. It tries to find the expected submit button attached to the form and click on it if available or fail if not available.

This action apply to *Submissible* Components.

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
submit myForm
----

[[reset]]
==== reset

This action is to *reset* a form. It tries to find the expected reset button attached to the form and click on it if available or fail if not available.

This action apply to *Resettable* Components.

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
reset myForm
----

[[switchOn]]
==== switchOn

Set in the same action as <<check>>. It's just a better word to suite components like Switch ...

This action applies on *Switchable* components.

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
switchOn darkTheme
----

[[switchOff]]
==== switchOff

Set in the same action as <<uncheck>>. It's just a better word to suite components like Switch ...

This action applies on *UnSwitchable* components.

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
switchOff darkTheme
----

[[select]]
==== select

This action does some assertions and verify that the item is *visible*, *not deactivated* and *not already selected*.
So for example if you try to select an item already selected an exception is thrown.

This action applies on *Item*.

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
select myItem_1, myItem_2
----


[[unselect]]
==== unselect

This action does some assertions and verify that the item is *visible*, *not deactivated* and *not already unselected*.
So for example if you try to unselect an item already unselected an exception is thrown.

This action applies on *Item*.

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
unselect myItem_1, myItem_2
----

==== on

This action is jut a pass through (a function who return the passed component).
It's here to improve readability of a test.


[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
include::{sourcedir}/test/groovy/sc/tyro/doc/InteractionTest.groovy[tags=on,indent=0]
----







