name: Publish documentation
on:
  push:
    branches: [ main ]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
      - name: Build Tyro
        run: ./mvnw clean package
      - name: Publish Documentation
        run: .github/actions/documentation.sh ${{ secrets.GITHUB_TOKEN }}