name: Publish documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'liberica'
          cache: 'maven'
      - name: Generate Documentation
        run: .github/actions/documentation.sh ${{ secrets.GITHUB_TOKEN }}

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ../gh-pages