name: Publish documentation
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'liberica'
          cache: 'maven'

      - name: Publishing
        run: .github/actions/documentation.sh ${{ secrets.GITHUB_TOKEN }}