name: Publish documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'liberica'
          cache: 'maven'
      - name: Generate Documentation
        run: .github/actions/documentation.sh ${{ secrets.GITHUB_TOKEN }}

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ../gh-pages